### ISSUE TITLE
Get ride off `undefined` property

### ISSUE THREAD

**Issue by whybe7** [code-node-gui/node-code#6]
https://github.com/code-node-gui/node-code/blob/18f7fe213e42d9dddc76f80ec773729376fd8eea/src/components/Output.jsx#L69
Get ride off `undefined` property

**Comment by tchi-sama** [comment]
it wasnt this problem , here all good , the problem was in the button component , on click , now all good

**Comment by whybe7** [comment]
Yes, no doubt of that, but you should link the pull request that solves this problem or at least mention it in your comment like #11
